server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
#  Для подключения к Postgres
# spring:
#   datasource:
#     url:
#     username:
#     password:
#     driver-class-name:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


